language: python

# sudo false implies containerized builds
sudo: false

python:
  # - "3.6"
  - "3.8"

before_install:
  # Here we download miniconda and install the dependencies
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  # - conda config --set channel_priority strict 
  - conda update -q conda
  - conda info -a
  - echo "Python version var"
  - echo $TRAVIS_PYTHON_VERSION
  # Edit the environment.yml file for the target Python version
  - sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' ./environment.yml
  - conda env create -f environment.yml
  - source activate mixsea

# install the package itself
install:
  - python setup.py install

# command to run tests
script:
  - python --version
  - pytest
  - black --check mixsea/

# safelist
#branches:
#  only:
#  - master
#  - stable
